import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{createChart,CandlestickSeries,HistogramSeries,LineSeries}from'lightweight-charts';
import'./styles.css';

const API='https://api.binance.com/api/v3';
const num=v=>Number(v||0),pct=v=>num(v),clamp=v=>Math.max(0,Math.min(99,Math.round(v)));
const fmt=v=>num(v).toLocaleString(undefined,{maximumFractionDigits:8});

function ema(values,period){const k=2/(period+1);let e=values[0]||0;return values.map((v,i)=>i?e=v*k+e*(1-k):e)}
function rsi(values,period=14){if(values.length<=period)return 50;let gain=0,loss=0;for(let i=1;i<=period;i++){const d=values[i]-values[i-1];gain+=Math.max(d,0);loss+=Math.max(-d,0)}let ag=gain/period,al=loss/period;for(let i=period+1;i<values.length;i++){const d=values[i]-values[i-1];ag=(ag*(period-1)+Math.max(d,0))/period;al=(al*(period-1)+Math.max(-d,0))/period}return al===0?100:100-100/(1+ag/al)}
function score(c,previous){const ch=Math.abs(pct(c.priceChangePercent)),vol=num(c.quoteVolume),trades=num(c.count);let s=20;if(ch>=8)s+=24;else if(ch>=5)s+=18;else if(ch>=3)s+=12;else if(ch>=1.5)s+=7;if(trades>=100000)s+=16;else if(trades>=50000)s+=12;else if(trades>=10000)s+=7;if(vol>=1e8)s+=18;else if(vol>=5e7)s+=13;else if(vol>=5e6)s+=8;if(previous){const vd=(vol-num(previous.quoteVolume))/Math.max(num(previous.quoteVolume),1)*100;if(Math.abs(vd)>=25)s+=10}return clamp(s)}
async function json(url){const r=await fetch(url);if(!r.ok)throw Error('Market data unavailable');return r.json()}

function Chart({symbol}){
 const ref=useRef(null),chart=useRef(null);
 useEffect(()=>{if(!ref.current)return;chart.current=createChart(ref.current,{layout:{background:{color:'#081017'},textColor:'#80949a'},grid:{vertLines:{color:'#102029'},horzLines:{color:'#102029'}},rightPriceScale:{borderColor:'#1a2a33'},timeScale:{borderColor:'#1a2a33',timeVisible:true},crosshair:{mode:1}});
 const c=chart.current,cs=c.addSeries(CandlestickSeries,{upColor:'#54f0c1',downColor:'#ff6681',borderVisible:false,wickUpColor:'#54f0c1',wickDownColor:'#ff6681'}),vs=c.addSeries(HistogramSeries,{priceFormat:{type:'volume'},priceScaleId:'',base:0});vs.priceScale().applyOptions({scaleMargins:{top:.8,bottom:0}});
 const ema20=c.addSeries(LineSeries,{color:'#7e9cff',lineWidth:1});let alive=true;
 (async()=>{try{const ks=await json(API+'/klines?symbol='+symbol+'&interval=5m&limit=240');if(!alive)return;const candles=ks.map(k=>({time:k[0]/1000,open:num(k[1]),high:num(k[2]),low:num(k[3]),close:num(k[4])}));cs.setData(candles);vs.setData(ks.map(k=>({time:k[0]/1000,value:num(k[5]),color:num(k[4])>=num(k[1])?'#54f0c166':'#ff668166'})));const closes=candles.map(x=>x.close),e=ema(closes,20);ema20.setData(candles.map((x,i)=>({time:x.time,value:e[i]})));c.timeScale().fitContent()}catch{}})();
 const ro=new ResizeObserver(()=>c.resize(ref.current.clientWidth,360));ro.observe(ref.current);return()=>{alive=false;ro.disconnect();c.remove()}},[symbol]);
 return <div ref={ref} className="tv-chart"/>
}

function App(){
 const[coins,setCoins]=useState([]),[news,setNews]=useState([]),[query,setQuery]=useState(''),[filter,setFilter]=useState('radar'),[selected,setSelected]=useState(null),[detail,setDetail]=useState(null),[updated,setUpdated]=useState(null),[error,setError]=useState(''),[history,setHistory]=useState({});
 async function load(){try{setError('');const all=await json(API+'/ticker/24hr');const market=all.filter(x=>x.symbol.endsWith('USDT')&&num(x.quoteVolume)>1e5).map(x=>({...x,radar:score(x,history[x.symbol])}));setCoins(market);setUpdated(new Date());setHistory(h=>{const n={...h};market.forEach(x=>n[x.symbol]={lastPrice:x.lastPrice,quoteVolume:x.quoteVolume});return n});try{const n=await fetch('/.netlify/functions/news');const t=n.headers.get('content-type')||'';if(n.ok&&t.includes('application/json'))setNews(await n.json())}catch{}}catch(e){setError(e.message)}}
 useEffect(()=>{load();const t=setInterval(load,30000);return()=>clearInterval(t)},[]);
 async function investigate(c){setSelected(c);setDetail(null);try{const[book,trades,ks]=await Promise.all([json(API+'/depth?symbol='+c.symbol+'&limit=100'),json(API+'/trades?symbol='+c.symbol+'&limit=500'),json(API+'/klines?symbol='+c.symbol+'&interval=5m&limit=240')]);const bid=book.bids.reduce((a,x)=>a+num(x[1]),0),ask=book.asks.reduce((a,x)=>a+num(x[1]),0),imb=(bid+ask)?(bid-ask)/(bid+ask)*100:0,buy=trades.filter(t=>!t.isBuyerMaker).length,sell=trades.length-buy,c=ks.map(k=>({time:k[0]/1000,open:num(k[1]),high:num(k[2]),low:num(k[3]),close:num(k[4]),volume:num(k[5])})),closes=c.map(x=>x.close),fast=ema(closes,9).at(-1),slow=ema(closes,21).at(-1),r=rsi(closes),last=c.at(-1),prev=c.at(-2),move=prev?(last.close-prev.close)/prev.close*100:0,volAvg=c.slice(-20,-1).reduce((a,x)=>a+x.volume,0)/19,vr=volAvg?last.volume/volAvg:1;
 let points=0;points+=fast>slow?25:-25;points+=r>=55?15:r<=45?-15:0;points+=imb>8?20:imb<-8?-20:0;points+=buy>sell+20?15:sell>buy+20?-15:0;points+=vr>1.8?(move>0?15:-15):0;const signal=points>=35?'LONG':points<=-35?'SHORT':'WAIT';setDetail({imb,buy,sell,fast,slow,r,move,vr,points,signal})}catch{setDetail({error:'Deep scan unavailable right now.'})}}
 const list=useMemo(()=>coins.filter(c=>c.symbol.toLowerCase().includes(query.toLowerCase())).filter(c=>filter==='radar'?c.radar>=35:filter==='pump'?pct(c.priceChangePercent)>=2:filter==='dump'?pct(c.priceChangePercent)<=-2:true).sort((a,b)=>filter==='dump'?pct(a.priceChangePercent)-pct(b.priceChangePercent):b.radar-a.radar).slice(0,80),[coins,query,filter]);
 return <div className="app"><header><div className="logo"><span>◈</span> CRYPTO<span>RADAR</span><small> AI / V3</small></div><div className="live"><i/> LIVE MARKET INTELLIGENCE <button onClick={load}>↻</button></div></header><main>
 <section className="hero"><div><div className="eyebrow">AI MARKET SCOUT / V3</div><h1>See the market.<br/><em>Read the signal.</em></h1><p>V3 adds an interactive candlestick chart and a transparent directional signal built from EMA trend, RSI momentum, order-book pressure, trade flow and volume expansion.</p><div className="disclaimer">⚠ LONG / SHORT is an algorithmic market signal, not a guarantee or personalized financial advice.</div></div><div className="radar"><div className="radar-ring r1"/><div className="radar-ring r2"/><div className="radar-ring r3"/><div className="radar-sweep"/><div className="radar-core">RADAR<br/><b>{coins.length||'—'}</b><small>MARKETS</small></div></div></section>
 <section className="stats"><div><b>{coins.length}</b><span>Markets scanned</span></div><div><b>{coins.filter(c=>c.radar>=70).length}</b><span>High anomalies</span></div><div><b>{coins.filter(c=>pct(c.priceChangePercent)>=5).length}</b><span>Strong up moves</span></div><div><b>{news.length}</b><span>News signals</span></div></section>
 <section className="workspace"><div className="toolbar"><div className="tabs">{[['radar','Radar'],['pump','Up moves'],['dump','Down moves'],['all','All']].map(([k,l])=><button key={k} className={filter===k?'active':''} onClick={()=>setFilter(k)}>{l}</button>)}</div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search any coin…"/></div>
 <div className="grid"><div className="panel markets"><div className="panel-head"><div><div className="eyebrow">01 / MARKET SCAN</div><h2>V3 Signal Radar</h2></div><span>{updated?updated.toLocaleTimeString():''}</span></div>{error?<div className="empty error">{error}</div>:<div className="coin-list">{list.map(c=><button className="coin" onClick={()=>investigate(c)} key={c.symbol}><span className="coin-name"><strong>{c.symbol.replace('USDT','')}</strong><small>USDT · {num(c.count).toLocaleString()} trades</small></span><span className="bar"><i style={{width:c.radar+'%'}}/></span><span className="coin-price">$ {fmt(c.lastPrice)}</span><span className={pct(c.priceChangePercent)>=0?'up':'down'}>{pct(c.priceChangePercent)>=0?'+':''}{pct(c.priceChangePercent).toFixed(2)}%</span><b className={'score s'+(c.radar>=70?'high':c.radar>=50?'mid':'low')}>{c.radar}</b></button>)}</div>}</div>
 <div className="side"><div className="panel"><div className="eyebrow">02 / NEWS INTELLIGENCE</div><h2>What is moving the market?</h2>{news.length?<div className="news">{news.slice(0,10).map((n,i)=><a key={n.link||i} href={n.link} target="_blank" rel="noreferrer"><span>{n.source}</span><strong>{n.title}</strong><small>{n.time}</small></a>)}</div>:<div className="empty">News feed is loading…</div>}</div><div className="panel methodology"><div className="eyebrow">03 / V3 SIGNAL ENGINE</div><h3>Direction with transparent inputs.</h3><p>LONG, SHORT or WAIT is derived from EMA 9/21 trend, RSI, order-book imbalance, recent buyer/seller trade count and 5-minute volume expansion.</p><div className="chips"><span>EMA 9/21</span><span>RSI</span><span>ORDER BOOK</span><span>TRADE FLOW</span><span>VOLUME</span></div></div></div></div></section></main>
 {selected&&<div className="modal" onClick={()=>{setSelected(null);setDetail(null)}}><div className="modal-card wide" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>{setSelected(null);setDetail(null)}}>×</button><div className="eyebrow">V3 TRADING TERMINAL</div><div className="symbol-head"><div><h2>{selected.symbol.replace('USDT','')} / USDT</h2><span className="live-price">$ {fmt(selected.lastPrice)} · 24h {pct(selected.priceChangePercent).toFixed(2)}%</span></div>{detail&&!detail.error&&<div className={'trade-signal '+detail.signal.toLowerCase()}><small>ALGORITHMIC SIGNAL</small><b>{detail.signal}</b><span>{Math.abs(detail.points)} / 100 conviction</span></div>}</div><Chart symbol={selected.symbol}/>{detail?.error?<p className="error">{detail.error}</p>:detail?<div className="signal-grid"><div><span>EMA 9 / 21</span><b>{fmt(detail.fast)} / {fmt(detail.slow)}</b></div><div><span>RSI</span><b>{detail.r.toFixed(1)}</b></div><div><span>Order-book</span><b className={detail.imb>=0?'up':'down'}>{detail.imb>=0?'+':''}{detail.imb.toFixed(1)}%</b></div><div><span>Buy / Sell trades</span><b>{detail.buy} / {detail.sell}</b></div><div><span>5m move</span><b className={detail.move>=0?'up':'down'}>{detail.move>=0?'+':''}{detail.move.toFixed(2)}%</b></div><div><span>Volume ratio</span><b>{detail.vr.toFixed(2)}×</b></div></div>:<div className="scan-line">Calculating directional signal…</div>}<p className="terminal-note">Signal logic is visible and rule-based. It can be wrong, especially during sudden news, liquidity shocks or thin markets. Use the chart and underlying data to make your own decision.</p></div></div>}
 </div>}
createRoot(document.getElementById('root')).render(<App/>);